# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is Kanath Buntoum
email: samuraikenny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is made to fullfill my requirements of posting a website for my web design online course. So I'm gonna post whatever I want LOL.
baseurl: "" # the subpath of your site, e.g. /blog
url: "kanathb.com" # the base hostname & protocol for your site
twitter_username: SnipingKendo
github_username:  kbuntoum

# Build settings
markdown: kramdown
